### ISSUE TITLE
Update usng.js?

### ISSUE THREAD

**Issue by csmoore** [Esri/position-analysis-js#42]
Not sure if we are actively maintaining this repo (since I think this functionality is part of Web App Builder or [one of the add-on widgets](https://github.com/Esri/solutions-webappbuilder-widgets) now), but if so, in passing, I happened to notice slightly never versions of this file:

http://dhost.info/usngweb/usng.js 

And what seems to be a more actively maintained repo at:

https://github.com/codice/usng.js

So just wanted to capture this here while I was thinking about it.

**Comment by csmoore** [comment]
Never heard back - closing this as unanswered/won't fix

**Comment by garys-esri** [comment]
Sorry I never replied. I think we're okay to close this issue.

If there is time and demand, I'd like to migrate the functionality in this repo to a Web AppBuilder widget. Web AppBuilder now includes usng.js as part of its built-in MGRS/USNG capabilities.

**Comment by csmoore** [comment]
Definitely not a biggie (and not even assigned to you anyway) - I am just spring cleaning issues/cobwebs. 

But that is a great idea - so I'll add that issue here just to track somewhere for now - thanks
