### ISSUE TITLE
Retire this repo and add as Web AppBuilder widget?

### ISSUE THREAD

**Issue by csmoore** [Esri/position-analysis-js#43]
https://github.com/Esri/position-analysis-js/issues/42#issuecomment-76397008

https://github.com/Esri/solutions-webappbuilder-widgets

**Comment by nfeuerstein** [comment]
Added to backlog.  Its a good idea.

**Comment by nfeuerstein** [comment]
On second thought, a lot of this functionality will exist with the "coordinate conversion" widget (upcoming project) which I believe Ben said the military team will own.  Additional functionality, such as creating features from tables could be discussed.
